name: Node.js CI
on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
            - name: Setup node
              uses: actions/setup-node@v6
              with:
                  node-version: 24.x
            - name: Install dependencies
              run: |
                  npm ci
                  npm ls
            - name: Run Test
              run: npm run test

              # FIXME: This always produces diffs of little numbers, see https://github.com/vercel/ncc/issues/831#issuecomment-1594540905. Don't test until resolved
              # - name: Validate dist
              #   run: |
              #       cp dist/index.js index_pr.js
              #       rm -r dist
              #       npm i -g @vercel/ncc
              #       npm run build
              #       npm run package
              #       diff dist/index.js index_pr.js
              #       if [ $? -ne 0 ]; then
              #           echo "Files differ."
              #           exit 0
              #       fi
