name: Node.js CI
on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
            - name: Setup node
              uses: actions/setup-node@v6
              with:
                  node-version: 25.9.0
            - name: Build Project
              run: |
                  rm -rf node_modules
                  npm ci
                  npm ls
                  npm run build
                  npm i -g @vercel/ncc
            - name: Validate dist
              run: |
                  cp dist/index.js index_pr.js
                  rm -r dist
                  npm run package
                  diff dist/index.js index_pr.js
                  if [ $? -ne 0 ]; then
                      echo "Files differ!"
                      exit 1
                  fi
            - name: Test Project
              run: npm run test
